Craig 881: add additionalText to deleteModal
IBM/icse-react-assets pull request #215
Opened 2023-10-06 18:24 UTC by terechc

2023-10-06 20:35 UTC, evpirnia requested changes

2023-10-06 20:35 UTC, evpirnia commented on src/components/Modals.js
> +      <p>{props.additionalText}</p>
need a conditional here so that it's not display if nullOrEmptyString (can use from lazy-z)

2023-10-09 14:32 UTC, jvallexm commented on src/components/Modals.js
> +  const hasAdditionalText = !isNullOrEmptyString(props.additionalText);
we don't need to assign this to a variable, you can change the modal return to
```
  additionalText={props.additionalText}

2023-10-09 14:32 UTC, jvallexm commented on src/components/Modals.js
> +        <div>{hasAdditionalText && props.additionalText}</div>
change here to `{props.additionalText && <div>{props.additionalText</div>}`

2023-10-09 20:14 UTC, jvallexm requested changes

2023-10-10 13:24 UTC, jvallexm approved these changes

2023-10-10 16:10 UTC, merged