added ErrorPage (similar to under construction page and stories) for CRAIG issue-944
IBM/icse-react-assets pull request #219
Opened 2023-10-19 22:10 UTC by Ay1man2

2023-10-19 22:57 UTC, evpirnia requested changes

2023-10-19 22:57 UTC, evpirnia commented on src/components/ErrorPage.js
> +const ErrorPage = () => {
et's change this to PageNotFound

2023-10-19 22:57 UTC, evpirnia commented on src/components/ErrorPage.js
> +      <h4>Error 404: Page Not Found</h4>
let's mimic IBM Cloud a bit here. 

change to "Unfortunately, we couldn’t find the page you were looking for, but here are some helpful places to start from:" then list links for Projects, About, and Tutorial. 

<img width="200" alt="Screenshot 2023-10-19 at 3 52 08 PM" src="https://github.com/IBM/icse-react-assets/assets/11401353/05a2fcd0-3860-41ef-98e7-75d5bc5fbf0a">

2023-10-19 22:57 UTC, evpirnia commented on src/components/ErrorPage.js
> +      <WarningAlt size="128" />
can we try this with the carbon Help icon instead? `<Help />`

2023-10-20 01:10 UTC, jvallexm commented
closing, needs to be implemented in craig

2023-10-20 01:10 UTC, closed without merging