Craig-927: added ClassicVlanForm and story
IBM/icse-react-assets pull request #222
Opened 2023-10-26 17:53 UTC by Pseusco

2023-10-26 19:31 UTC, evpirnia requested changes

2023-10-26 19:31 UTC, evpirnia commented on src/components/forms/ClassicVlanForm.js
> +      /**
format please with `npm run pretty`

2023-10-26 21:10 UTC, Ay1man2 commented on storybook/src/stories/Forms/ClassicVlanForm.stories.js
> +      type: { required: false },
change `required: true`

2023-10-26 21:10 UTC, Ay1man2 commented on storybook/src/stories/Forms/ClassicVlanForm.stories.js
> +      type: { required: false },
change `required: true`

2023-10-26 21:11 UTC, Ay1man2 commented on storybook/src/stories/Forms/ClassicVlanForm.stories.js
> +      type: { required: false },
change `required: true`

2023-10-27 13:31 UTC, jvallexm commented
needs merge, bump version to 1.2.11

2023-10-27 13:32 UTC, jvallexm requested changes

2023-10-27 13:32 UTC, jvallexm commented on src/components/forms/ClassicVlanForm.js
> +            groups={this.props.vlanTypes}
this can always be `PUBLIC` and `PRIVATE`

should be title case when rendered, all caps in state

2023-10-27 17:55 UTC, jvallexm approved these changes

2023-10-27 17:56 UTC, jvallexm requested changes

2023-10-27 17:56 UTC, jvallexm commented on src/components/forms/ClassicVlanForm.js
> +            groups={["PUBLIC", "PRIVATE"].map(vlanTypeTitleCase)}
Just hardcode here, it'll always be uppercase in state

2023-10-27 18:04 UTC, jvallexm commented on src/components/forms/ClassicVlanForm.js
> +            value={vlanTypeTitleCase(this.state.type)}
`titleCase(this.state.typ`

2023-10-27 18:04 UTC, jvallexm commented on src/components/forms/ClassicVlanForm.js
> +            groups={["PUBLIC", "PRIVATE"].map(vlanTypeTitleCase)}
`["Public", "Private"]`

2023-10-27 19:35 UTC, jvallexm approved these changes

2023-10-27 19:42 UTC, evpirnia approved these changes

2023-10-27 19:50 UTC, Ay1man2 approved these changes

2023-10-27 20:12 UTC, merged