Vsi hotfixes
IBM/icse-react-assets pull request #54
Opened 2023-04-05 16:26 UTC by aisaly

- Added Modal story under VsiForm
- Smaller fields in modal to fit
- VsiForm state is image instead of image_name now
- Flavors -> Profiles

2023-04-05 17:26 UTC, isaaceichelberger requested changes

2023-04-05 17:26 UTC, isaaceichelberger commented on src/components/forms/VsiForm.js
> -            invalid={this.props.invalidCallback(this.state)}
bring this back or change it to something that checks if null or empty string so it's marked as invalid when it is invalid

2023-04-05 17:26 UTC, isaaceichelberger commented on src/components/forms/VsiForm.js
cant comment on the line but handleInputChange is where `subnet` is getting added unncessarily, add a check for if `isTeleport` and from there either add `subnet` or `subnets` to the obj that goes into state

2023-04-05 18:12 UTC, jvallexm approved these changes

2023-04-06 20:26 UTC, isaaceichelberger approved these changes

2023-04-06 20:28 UTC, merged